
services:

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SECRET: ${SECRET}               # build‑time ARG preserved
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET: ${SECRET}
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_SERVER: ${VUE_APP_SERVER}  # build‑time ARG preserved
    env_file:
      - .env
    environment:
      VUE_APP_SERVER: ${VUE_APP_SERVER}
    depends_on:
      - backend
    ports:
      - "3000:80"


volumes:
  db_data:
