services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      args:
        SECRET: ${SECRET}
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET: ${SECRET}
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

###########################################
  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_SERVER: ${VUE_APP_SERVER}
    env_file:
      - .env
    environment:
      VUE_APP_SERVER: ${VUE_APP_SERVER}
      WATCHPACK_POLLING: true

    ports:
      - "8080:8080"
    depends_on:
      - backend
    command: npm run serve
    volumes:
      - ./frontend:/app
      - /app/node_modules


###########################################
###########################################
  mongo_db:
    image: mongo:latest
    env_file:
      - .env
    # environment:
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"



volumes:
  db_data:
  mongo_data: